export const CATEGORIES = ['Skin Care', 'Massage', 'Nails', 'Hair', 'Waxing', 'Packages']

export const SERVICES = [
  { name: 'Advanced Skin Care Facial', category: 'Skin Care', duration: 75,  price: 'Price TBC', description: 'Deep cleansing and rejuvenating facial treatment' },
  { name: 'Anti-Aging Facial',         category: 'Skin Care', duration: 60,  price: 'Price TBC', description: 'Reduce fine lines and restore youthful radiance' },
  { name: 'Brightening Facial',        category: 'Skin Care', duration: 60,  price: 'Price TBC', description: 'Even skin tone and reveal your natural glow' },
  { name: 'Acne Treatment Facial',     category: 'Skin Care', duration: 60,  price: 'Price TBC', description: 'Targeted treatment for clearer, healthier skin' },
  { name: 'Relaxation Massage',        category: 'Massage',   duration: 60,  price: 'Price TBC', description: 'Full-body tension release for total tranquility' },
  { name: 'Deep Tissue Massage',       category: 'Massage',   duration: 90,  price: 'Price TBC', description: 'Targeted relief for deep muscle tension' },
  { name: 'Body Scrub & Wrap',         category: 'Massage',   duration: 90,  price: 'Price TBC', description: 'Exfoliating and nourishing full body treatment' },
  { name: 'Aromatherapy Massage',      category: 'Massage',   duration: 60,  price: 'Price TBC', description: 'Soothing massage with premium essential oils' },
  { name: 'Manicure',                  category: 'Nails',     duration: 45,  price: 'Price TBC', description: 'Classic nail care and polish for beautiful hands' },
  { name: 'Pedicure',                  category: 'Nails',     duration: 45,  price: 'Price TBC', description: 'Relaxing foot treatment and nail polish' },
  { name: 'Gel Nails',                 category: 'Nails',     duration: 60,  price: 'Price TBC', description: 'Long-lasting gel polish for a flawless finish' },
  { name: 'Nail Art',                  category: 'Nails',     duration: 60,  price: 'Price TBC', description: 'Creative designs to express your unique style' },
  { name: 'Mani-Pedi Combo',           category: 'Nails',     duration: 90,  price: 'Price TBC', description: 'Our most-booked complete hand and foot treatment' },
  { name: 'Haircut & Styling',         category: 'Hair',      duration: 60,  price: 'Price TBC', description: 'Expert cut and style to suit your look' },
  { name: 'Keratin Treatment',         category: 'Hair',      duration: 120, price: 'Price TBC', description: 'Smooth, frizz-free hair for weeks' },
  { name: 'Hair Colouring',            category: 'Hair',      duration: 120, price: 'Price TBC', description: 'Vibrant, professional colour results' },
  { name: 'Blowdry & Finish',          category: 'Hair',      duration: 45,  price: 'Price TBC', description: 'Salon-perfect blowout and styling' },
  { name: 'Full Body Wax',             category: 'Waxing',    duration: 90,  price: 'Price TBC', description: 'Complete smooth skin waxing treatment' },
  { name: 'Eyebrow Wax & Tint',        category: 'Waxing',    duration: 30,  price: 'Price TBC', description: 'Perfectly shaped and defined brows' },
  { name: 'Lip & Facial Wax',          category: 'Waxing',    duration: 30,  price: 'Price TBC', description: 'Precise hair removal for a clean finish' },
  { name: 'Couple Package',            category: 'Packages',  duration: 120, price: 'Price TBC', description: 'Romantic spa experience for two — perfect for gifting' },
  { name: 'Bridal Package',            category: 'Packages',  duration: 180, price: 'Price TBC', description: 'Full beauty prep for brides' },
  { name: 'Birthday Pamper Package',   category: 'Packages',  duration: 120, price: 'Price TBC', description: 'The perfect celebration treat' },
  { name: 'Full Day Retreat',          category: 'Packages',  duration: 480, price: 'Price TBC', description: 'An entire day of blissful treatments' },
]
